name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set visable
      run: echo "VERSION=$(git describe --tags)" >> $GITHUB_ENV
    - name: ECHO visable
      run: echo $GITHUB_ENV
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Composer update
      run: composer self-update --stable
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --optimize-autoloader
    - name: Package Discover
      run: php artisan package:discover
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
#    - name: Push to Tencent Docker Hub
#      uses: docker/build-push-action@v2
#      with:
#        username: ${{ secrets.TENCENT_REGISTRY_PASSWORD }}
#        password: ${{ secrets.TENCENT_REGISTRY_USERNAME }}
#        registry: aidong-backend.tencentcloudcr.com
#        repository: aidong-backend.tencentcloudcr.com/aidong/blog
#        tag_with_ref: true
    - name: Build Image
      run: docker build -t aidong-backend.tencentcloudcr.com/aidong/blog:$VERSION .
    - name: Login to tencnet docker image registry
      run: echo "${{ secrets.TENCENT_REGISTRY_PASSWORD }}" |  docker login aidong-backend.tencentcloudcr.com --username 100008616442 --password-stdin
    - name: Push Image to tencent docker image registry
      run: docker push aidong-backend.tencentcloudcr.com/aidong/blog:$VERSION
